services:
  api:
    build:
      context: ./
      dockerfile: ./simplauth-api/Dockerfile

    ports:
      - "3000:3000"

    volumes:
      - ./simplauth-api:/app/simplauth-api
      - /app/node_modules
      - /app/simplauth-api/node_modules

    working_dir: /app/simplauth-api
    command: "npm run dev"

    env_file:
      - ./simplauth-api/.env

    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://docker:docker@postgres:5432/simplauth-zero}

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "postgres:16"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: simplauth-zero

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U docker -d simplauth-zero" ]
      interval: 3s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./
      dockerfile: ./simplauth-web/Dockerfile

    ports:
      - "5173:5173"


    depends_on:
      - postgres

volumes:
  postgres_data: {}
